### ISSUE TITLE
Couldn't install VBoxManage while running Vagrant

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/imouto#60]
I've got this after I run ```vagrant up```

![image](https://user-images.githubusercontent.com/7658430/81112895-bc916b80-8ef5-11ea-8bf3-5aa435b29d9f.png)

I wasn't able to access http://localhost:8080/ as well (maybe because of the VBox):

![image](https://user-images.githubusercontent.com/7658430/81113072-024e3400-8ef6-11ea-9394-421d6811ce68.png)

**Comment by Yorwba** [comment]
Searching for "vboxmanage vt-x is not available", I found [someone on StackOverflow having the same problem](https://stackoverflow.com/q/37955942). Maybe the answer there works for you. It looks like you'll need to modify some Windows settings.

Not being able to connect to `localhost:8080` is the expected result if the server isn't running.

**Comment by RyckRichards** [comment]
They doesn't work on Windows 7... Going to investigate some more

**Comment by RyckRichards** [comment]
![image](https://user-images.githubusercontent.com/7658430/81123071-a2ad5400-8f08-11ea-9b35-dcd7c99fcad4.png)

**Comment by RyckRichards** [comment]
I followed instructions on [https://forums.virtualbox.org/viewtopic.php?f=6&t=87752](https://forums.virtualbox.org/viewtopic.php?f=6&t=87752)

1st attempt (no rebooting) - it said I didn't have PowerShell 3 installed (which I had installed before)

2nd attempt (after rebooting) - got the same error

```There was an error while executing VBoxManage, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "81e9704f-8169-4ab1-a455-c6a852a21423", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole```

**Comment by AndiPersti** [comment]
Please tell us what processor you have in your computer. See https://www.intel.com/content/www/us/en/support/articles/000006059/processors.html for finding it out.

**Comment by jiru** [comment]
@RyckRichards The error says that your computer’s CPU doesn’t support VT-x. VT-x is a feature that allows running virtual machines at a decent speed.

Now, the error could be the result of Windows disabling VT-x for some reason even though your CPU have it, or it could be because your CPU just doesn’t have it. In the latter case, it’s not worth trying to get it work. Without VT-x, I can tell you even if you manage to run the virtual machine, it will be *really really* slow, barely usable.

**Comment by RyckRichards** [comment]
Thank you, guys!

@AndiPersti 
![image](https://user-images.githubusercontent.com/7658430/81150183-de223f80-8f55-11ea-8ac3-6441bfd2d6cf.png)


@jiru - as far this new computer has 2GB RAM, I set ```v.memory = 128```. Going to try 256 and 512 then.

**Comment by RyckRichards** [comment]
In both cases, I got this after initializing VM 

![image](https://user-images.githubusercontent.com/7658430/81152519-643f8580-8f58-11ea-874e-d33994a0c5ee.png)

**Comment by AndiPersti** [comment]
Here's the specification for your processor: https://ark.intel.com/content/www/us/en/ark/products/42925/intel-pentium-processor-t4500-1m-cache-2-30-ghz-800-mhz-fsb.html. There it says: 
````
 Intel® Virtualization Technology (VT-x)     No
````
So you can't use the VM on your computer.

**Comment by RyckRichards** [comment]
Oh, I see!

So should I use XAMPP or give up? Is there another way to use Imouto?

**Comment by AndiPersti** [comment]
> So should I use XAMPP or give up?

I don't know anything about XAMPP so I can't help you here.

> Is there another way to use Imouto?

Theoretically you could go through all the steps in the ansible playbook and do all the installations and configurations manually (as far as they are possible on Windows). But I guess that's not easy if you do not have much experience with all the programs involved.

**Comment by trang** [comment]
@AndiPersti XAMPP is just a bundle of PHP, MySQL and Apache. I made Ricardo install it during one of the video calls to discuss the coding event and we almost got to the point where he could run Tatoeba locally (not with all the features, but enough so that he could work on very simple issues). There was just the database missing. 

@RyckRichards You'll have to use XAMPP. In case you don't have your old computer anymore:

- Install [XAMPP version 7.3.2](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.3.2/xampp-portable-win32-7.3.2-0-VC15-installer.exe/download).
- Next, do a `git clone https://github.com/RyckRichards/tatoeba2.git` in the `C:\xampp\htdocs` folder.
- After that we can have a video call so that I can guide you again on the remaining configuration.

**Comment by RyckRichards** [comment]
Thanks a lot, @trang and I'm really sorry for causing you so much trouble, @Tatoeba/developers

**Comment by trang** [comment]
We managed to set up Tatoeba for Ricardo. I'm closing this.
