### ISSUE TITLE
Vagrant file unable to locate fstab in some OSX versions

### ISSUE THREAD

**Issue by ngfuwai** [Tatoeba/imouto#62]
When I downloaded imouto for the first time, I found out that the Vagrantfile was unable to locate my fstab file. This is because my fstab file is named `fstab.hd` in my etc file. I managed to fix the issue by changing all instances of `/etc/fstab` to `/etc/fstab.hd` in the Vagrantfile. My OS is OSX El Capitan version 10.11.6

**Comment by jiru** [comment]
Hi Tiger, thanks for reporting the issue. :blush: 

I don’t use OSX so I’m not familiar with this system, but from what I’ve seen on the web, it looks like `/etc/fstab.hd` is ignored (it contains a warning message about its obsolete status) and that `/etc/fstab` is still used by OSX, given that you create it.

Could you confirm that changing all instances of `/etc/fstab` to `/etc/fstab.hd` in the Vagrantfile makes automouting working, as opposed to merely removing "No such file"-like errors?

**Comment by ngfuwai** [comment]
@jiru  Sorry for the delayed reply. Instead of modifying the Vagrantfile, a better solution might be to create a new fstab file under /etc/ for each MAC user. This way the linux users would not encounter new difficulties.

**Comment by ngfuwai** [comment]
I tested this solution on my computer and was successful. My OS is OSX El Capitan version 10.11.6

**Comment by AndiPersti** [comment]
> @jiru Sorry for the delayed reply. Instead of modifying the Vagrantfile, a better solution might be to create a new fstab file under /etc/ for each MAC user. This way the linux users would not encounter new difficulties.

Maybe I'm misunderstanding you, but you need to create `/etc/fstab` on your side, see https://github.com/Tatoeba/imouto#using-nfs-unixmacos

**Comment by jiru** [comment]
@ngfuwai Thanks for clarifying! :+1:

Maybe we can clarify in the README that MacOS users need to create /etc/fstab if it doesn’t exists? @ngfuwai If you think that would have helped you, feel free to open a pull request to say so in the README of imouto.

**Comment by mimzivvimzi** [comment]
Hi,
I ran into a similar/the same issue, but I don't quite understand how to fix it.  When I did "vagrant up" everything else was successful except for this at the very end:

grep: /etc/fstab: No such file or directory

How should I fix this?

**Comment by jiru** [comment]
@mimzivvimzi You can ignore this error for now. The VM is should be working already, it’s just that automatic mounting of the directory `Tatoeba` didn’t work. After following the instructions of [this section](https://github.com/Tatoeba/imouto#using-nfs-unixmacos), and if `mount Tatoeba/` works, then the error will disappear and you won’t have to run `mount Tatoeba/` every time you do `vagrant up`.

**Comment by mimzivvimzi** [comment]
Ok, thanks.  I'm trying to read through the instructions, but I don't understand this line: "Add the following line to your /etc/fstab:"

I understand that I have to change the path to my Imouto on my laptop, but where am I putting this?  Terminal?
# Change /your/path/to/imouto/Tatoeba/ to the actual path of Imouto
localhost:/home/vagrant/Tatoeba /your/path/to/imouto/Tatoeba/ nfs noauto,user,exec,port=8049,soft,timeo=10

**Comment by AndiPersti** [comment]
On a Mac you have to create the file `/etc/fstab` if it doesn't already exist and append that line to it.

In the terminal the command 
````
echo 'localhost:/home/vagrant/Tatoeba /your/path/to/imouto/Tatoeba/ nfs noauto,user,exec,port=8049,soft,timeo=10' | sudo tee -a /etc/fstab
````
would create the file if necessary and add the line (don't forget to replace your path).

Or you use the text editor of your choice.

**Comment by mimzivvimzi** [comment]
What happens if you accidentally copy and paste the wrong line?  I looked it up and pasted it into TextEdit.  Then, I came back a day later and copied/pasted the wrong line (without my path...I know).  

These were the steps:
echo 'localhost:/home/vagrant/Tatoeba /your/path/to/imouto/Tatoeba/ nfs noauto,user,exec,port=8049,soft,timeo=10' | sudo tee -a /etc/fstab

(I put in my password)
(I realize I made a mistake)

echo 'localhost:/home/vagrant/Tatoeba/Users/(name)/imouto/Tatoeba/nfs' noauto,user,exec,port=8049,soft,timeo=10 | sudo tee -a /etc/fstab
(put in my password)

./mount.sh -M ./Tatoeba /home/vagrant/Tatoeba/
'sshfs' not found! Please install it first!

mount Tatoeba/
mount: Tatoeba/: unknown special file or file system.

**Comment by jiru** [comment]
> What happens if you accidentally copy and paste the wrong line?

It won’t hurt. It will just make things not work. By the way, a new line will be appended every time you run `sudo tee -a /etc/fstab`, so you might have multiple lines in your `/etc/fstab`. Try to edit `/etc/fstab` with a text editor to have a complete view of the contents of the file. It should contain just one line.

> mount: Tatoeba/: unknown special file or file system.

This is likely because of

> echo 'localhost:/home/vagrant/Tatoeba/Users/(name)/imouto/**Tatoeba/nfs**' noauto,user,exec,port=8049,soft,timeo=10 | sudo tee -a /etc/fstab

`nfs` should be surrounded by spaces. It’s important to separate each element of the line with spaces. The line should be something like:
```
localhost:/home/vagrant/Tatoeba /Users/(name)/imouto/Tatoeba nfs noauto,user,exec,port=8049,soft,timeo=10
```

**Comment by jiru** [comment]
This should no longer be a problem with Tatovm, see 6a295b267e15e298ff65dac6de129886ad91986d.
