### ISSUE TITLE
Call to WHvSetupPartition failed during vagrant up

### ISSUE THREAD

**Issue by githubshrek** [Tatoeba/imouto#73]
I'm trying to install the development setup for the first time and I get a "Call to WHvSetupPartition failed" error during vagrant up. Any ideas? Let me know what more information you need to be able to help.

![image](https://user-images.githubusercontent.com/7943077/112903952-8601a800-90e8-11eb-9fe6-a52cc554d4cd.png)

**Comment by jiru** [comment]
About the WHvSetupPartition error, this error comes from VirtualBox, which is executed in the background when running `vagrant up`. A quick search suggests that following [these instructions](https://forums.virtualbox.org/viewtopic.php?f=1&t=62339) could help, especially the part about the `bcdedit` command.

While this is unrelated to the above error, I suggest running `vagrant box update` because you are running a quite old version of the VM. As this destroys the VM, make sure you don’t have anything important inside it, such as uncomitted code.

**Comment by githubshrek** [comment]
Thanks for your help. I'm making progress, I think, in that the error messages are different!

I am now using:
* Vagrant 2.2.14
* VirtualBox 6.1
* tatoeba box 0.0.12

The following is the error:
![image](https://user-images.githubusercontent.com/7943077/113036549-c3237400-9194-11eb-8edd-20971543b067.png)

I try to run the GUI at the same time which I understand is at http://localhost:8080/ but nothing there other than "This site cannot be reached".

Any ideas?

**Comment by githubshrek** [comment]
Thanks for your help. I tried to open the VirtualBox Manager, clicked on "Add", but I'm not sure what file to point it at:
![image](https://user-images.githubusercontent.com/7943077/113055771-464fc480-91ab-11eb-822e-8faff4c57cb2.png)

**Comment by jiru** [comment]
You don't need to click Add, the VM is already added in VirtualBox as imouto_default_something. When you run `vagrant up`, vagrant is actually adding and starting the VM behind the scenes using VirtualBox.

As shown on your screenshot, the VM state is "Aborted". Maybe VirtualBox can tell you more about that. You can also try to restart the VM from within VirtualBox.

**Comment by githubshrek** [comment]
Thanks for all your help.

I have to say I'm pretty discouraged. I'm an experienced PHP developer, but haven't got much a clue what I'm doing when it comes to VirtualBox, Vagrant and so forth. The concept of these things is great, and when they work, I agree they are amazing, and can give a one-click "working everywhere" experience. Currently though, I am completely blocked from being able to contribute at all to the project. I will keep pushing a bit on this whole Vagrant way of working, but I kind of think I will also take a look at the old school way of just running the Tatoeba code and CakePHP and setting up the database.

It's not your fault it's not working.

OK, back to trying to get imouto setup:

You say I don't need to click "Add". OK, so what do I click?

You say that VirtualBox can tell me more about the fact that it is "Aborted". How? Where?

You say I can try to restart the VM from within VirtualBox. No idea how to do that. I saw "Add" which seemed to me the right way, but apparently it's not.

![image](https://user-images.githubusercontent.com/7943077/113485065-0ab74200-94ac-11eb-8bc2-f9fd033f1545.png)

 Thanks for any help.

**Comment by jiru** [comment]
I understand your frustration. You have to use a buggy tool you are not familiar with in order to install a technology you are otherwise familiar with. I feel sorry to have you go through this.

About Virtualbox, I am sorry for not making myself very clear in my last comment.

> You say that VirtualBox can tell me more about the fact that it is "Aborted". How? Where?

I don’t know, I just meant to look around for any clue.

> You say I can try to restart the VM from within VirtualBox. No idea how to do that. I saw "Add" which seemed to me the right way, but apparently it's not.

In the Virtualbox window, the left panel shows a list of all your virtual machines. You can start, stop or pause any of them by right-clicking. From what I can see from your screenshots, you did restart the imouto VM. When you do it from the Virtualbox window, a new window appears showing the screen of that VM. This is where the "kernel panic" message was displayed. Normally it would just boot up the system, be it Windows, Mac, Android etc. and you really get a "computer inside your computer" in that very window.

To double check, I just installed a new instance of Imouto on my computer and it worked, so I think the problem comes from Windows or your setup. I am not very knowledgeable about Windows (or Virtualbox), so it is hard for me to give you precise instructions. It can merely guess:

1. I can see a number of "Aborted" other VMs in your screenshot, so maybe these are affected by the same issue as well.
2. Again from your screenshot, I can also see an "Invalid settings detected" message at the bottom of the Settings window of Virtualbox, maybe that’s related?
3. Are you running the latest version of Virtualbox?

> I kind of think I will also take a look at the old school way of just running the Tatoeba code and CakePHP and setting up the database.

Well, it is also possible to install a "basic" environment yourself without Vagrant, by installing and setting up nginx, PHP 7.3, mariadb and Manticore directly on your machine. It will be "basic" because some features won’t work, like language autodetection and transcription, but it should just work for the most part. If you want to go this route, here is a quick and dirty howto. Look at the Ansible roles (under `ansible/roles/` in the imouto repository). These roles are the recipes to install and setup each component. When building the VM, these roles are normally executed in sequence as defined in `ansible/tatoeba.tasks.yml`. For example the file `ansible/roles/setup_database/tasks/create_db.yml` initializes the database using a sequence of shell commands. The variables between double square brackets are defined in `ansible/host_vars/default`. Each role calls `tasks/main.yml`, which may call other `tasks/*.yml` files. So you want to read what’s in these files and more or less manually execute what they are doing under your Windows environment. If you use git bash (which I highly recommend), many of the commands could work as-is. Note that many of the .yml files include Ansible commands that are not just raw shell commands but an abstraction of that. While most of them are quite self-explanatory, you can look up Ansible documentation when in doubt.

**Comment by githubshrek** [comment]
Thanks for your help. I'm at least becoming more and more experienced in vagrant and VirtualBox manager, reading forums, etc.

I don't have anything working yet, but I'm trying all the suggestions I see from things like:
https://www.google.com/search?q=vagrant+hangs+at+ssh+auth+method&rlz=1C1CHBD_enBE815BE815&oq=vagrant+hangs+at+ssh+auth+method&aqs=chrome.0.69i59j0i22i30l4j69i60l2j69i61.10439j1j7&sourceid=chrome&ie=UTF-8

Eventually I guess I'll get it to work. As I said before it's ironic that the whole point of this vagrant and VirtualBox stuff is to eliminate the "it works on my machine" differences.

**Comment by githubshrek** [comment]
After many many hours of the usual IT determined struggles, I am pleased to report I finally got things working. I installed every latest version I could, struggled getting Ansible properly installed, tried installing half a dozen different Ubuntu versions in Virtual Box (where I planned to run the imouto box). The final thing which worked was turning off all the things mentioned here: https://forums.virtualbox.org/viewtopic.php?f=6&t=92776

Now, I have Tatoeba successfully working locally:
![image](https://user-images.githubusercontent.com/7943077/114284568-14631b80-9a51-11eb-8066-30a203613a05.png)

I saw Docker wasn't happy, but that's a problem for another day (probably Monday). 

Thanks for your help!
